In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Explore Data Analysis

In [2]:
df = pd.read_csv("Datasets/Training.csv")

In [3]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB

In [5]:
pd.set_option('display.max_rows', None)
df.isnull().sum()

itching                           0
skin_rash                         0
nodal_skin_eruptions              0
continuous_sneezing               0
shivering                         0
chills                            0
joint_pain                        0
stomach_pain                      0
acidity                           0
ulcers_on_tongue                  0
muscle_wasting                    0
vomiting                          0
burning_micturition               0
spotting_ urination               0
fatigue                           0
weight_gain                       0
anxiety                           0
cold_hands_and_feets              0
mood_swings                       0
weight_loss                       0
restlessness                      0
lethargy                          0
patches_in_throat                 0
irregular_sugar_level             0
cough                             0
high_fever                        0
sunken_eyes                       0
breathlessness                    0
sweating                          0
dehydration                       0
indigestion                       0
headache                          0
yellowish_skin                    0
dark_urine                        0
nausea                            0
loss_of_appetite                  0
pain_behind_the_eyes              0
back_pain                         0
constipation                      0
abdominal_pain                    0
diarrhoea                         0
mild_fever                        0
yellow_urine                      0
yellowing_of_eyes                 0
acute_liver_failure               0
fluid_overload                    0
swelling_of_stomach               0
swelled_lymph_nodes               0
malaise                           0
blurred_and_distorted_vision      0
phlegm                            0
throat_irritation                 0
redness_of_eyes                   0
sinus_pressure                    0
runny_nose                        0
congestion                        0
chest_pain                        0
weakness_in_limbs                 0
fast_heart_rate                   0
pain_during_bowel_movements       0
pain_in_anal_region               0
bloody_stool                      0
irritation_in_anus                0
neck_pain                         0
dizziness                         0
cramps                            0
bruising                          0
obesity                           0
swollen_legs                      0
swollen_blood_vessels             0
puffy_face_and_eyes               0
enlarged_thyroid                  0
brittle_nails                     0
swollen_extremeties               0
excessive_hunger                  0
extra_marital_contacts            0
drying_and_tingling_lips          0
slurred_speech                    0
knee_pain                         0
hip_joint_pain                    0
muscle_weakness                   0
stiff_neck                        0
swelling_joints                   0
movement_stiffness                0
spinning_movements                0
loss_of_balance                   0
unsteadiness                      0
weakness_of_one_body_side         0
loss_of_smell                     0
bladder_discomfort                0
foul_smell_of urine               0
continuous_feel_of_urine          0
passage_of_gases                  0
internal_itching                  0
toxic_look_(typhos)               0
depression                        0
irritability                      0
muscle_pain                       0
altered_sensorium                 0
red_spots_over_body               0
belly_pain                        0
abnormal_menstruation             0
dischromic _patches               0
watering_from_eyes                0
increased_appetite                0
polyuria                          0
family_history                    0
mucoid_sputum                     0
rusty_sputum                      0
lack_of_concentration             0
visual_disturbances               0
receiving_blood_transfusion       0
receiving_unsterile_injections    0
coma                              0
stomach_bleeding                  0
distention_of_abdomen             0
history_of_alcohol_consumption    0
fluid_overload.1                  0
blood_in_sputum                   0
prominent_veins_on_calf           0
palpitations                      0
painful_walking                   0
pus_filled_pimples                0
blackheads                        0
scurring                          0
skin_peeling                      0
silver_like_dusting               0
small_dents_in_nails              0
inflammatory_nails                0
blister                           0
red_sore_around_nose              0
yellow_crust_ooze                 0
prognosis                         0
dtype: int64

In [6]:
df.dtypes

itching                            int64
skin_rash                          int64
nodal_skin_eruptions               int64
continuous_sneezing                int64
shivering                          int64
chills                             int64
joint_pain                         int64
stomach_pain                       int64
acidity                            int64
ulcers_on_tongue                   int64
muscle_wasting                     int64
vomiting                           int64
burning_micturition                int64
spotting_ urination                int64
fatigue                            int64
weight_gain                        int64
anxiety                            int64
cold_hands_and_feets               int64
mood_swings                        int64
weight_loss                        int64
restlessness                       int64
lethargy                           int64
patches_in_throat                  int64
irregular_sugar_level              int64
cough                              int64
high_fever                         int64
sunken_eyes                        int64
breathlessness                     int64
sweating                           int64
dehydration                        int64
indigestion                        int64
headache                           int64
yellowish_skin                     int64
dark_urine                         int64
nausea                             int64
loss_of_appetite                   int64
pain_behind_the_eyes               int64
back_pain                          int64
constipation                       int64
abdominal_pain                     int64
diarrhoea                          int64
mild_fever                         int64
yellow_urine                       int64
yellowing_of_eyes                  int64
acute_liver_failure                int64
fluid_overload                     int64
swelling_of_stomach                int64
swelled_lymph_nodes                int64
malaise                            int64
blurred_and_distorted_vision       int64
phlegm                             int64
throat_irritation                  int64
redness_of_eyes                    int64
sinus_pressure                     int64
runny_nose                         int64
congestion                         int64
chest_pain                         int64
weakness_in_limbs                  int64
fast_heart_rate                    int64
pain_during_bowel_movements        int64
pain_in_anal_region                int64
bloody_stool                       int64
irritation_in_anus                 int64
neck_pain                          int64
dizziness                          int64
cramps                             int64
bruising                           int64
obesity                            int64
swollen_legs                       int64
swollen_blood_vessels              int64
puffy_face_and_eyes                int64
enlarged_thyroid                   int64
brittle_nails                      int64
swollen_extremeties                int64
excessive_hunger                   int64
extra_marital_contacts             int64
drying_and_tingling_lips           int64
slurred_speech                     int64
knee_pain                          int64
hip_joint_pain                     int64
muscle_weakness                    int64
stiff_neck                         int64
swelling_joints                    int64
movement_stiffness                 int64
spinning_movements                 int64
loss_of_balance                    int64
unsteadiness                       int64
weakness_of_one_body_side          int64
loss_of_smell                      int64
bladder_discomfort                 int64
foul_smell_of urine                int64
continuous_feel_of_urine           int64
passage_of_gases                   int64
internal_itching                   int64
toxic_look_(typhos)                int64
depression                         int64
irritability                       int64
muscle_pain                        int64
altered_sensorium                  int64
red_spots_over_body                int64
belly_pain                         int64
abnormal_menstruation              int64
dischromic _patches                int64
watering_from_eyes                 int64
increased_appetite                 int64
polyuria                           int64
family_history                     int64
mucoid_sputum                      int64
rusty_sputum                       int64
lack_of_concentration              int64
visual_disturbances                int64
receiving_blood_transfusion        int64
receiving_unsterile_injections     int64
coma                               int64
stomach_bleeding                   int64
distention_of_abdomen              int64
history_of_alcohol_consumption     int64
fluid_overload.1                   int64
blood_in_sputum                    int64
prominent_veins_on_calf            int64
palpitations                       int64
painful_walking                    int64
pus_filled_pimples                 int64
blackheads                         int64
scurring                           int64
skin_peeling                       int64
silver_like_dusting                int64
small_dents_in_nails               int64
inflammatory_nails                 int64
blister                            int64
red_sore_around_nose               int64
yellow_crust_ooze                  int64
prognosis                         object
dtype: object

In [7]:
df.describe()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
count,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,...,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000
mean,0.137805,0.159756,0.021951,0.045122,0.021951,0.162195,0.139024,0.045122,0.045122,0.021951,...,0.021951,0.021951,0.021951,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171,0.023171
std,0.344730,0.366417,0.146539,0.207593,0.146539,0.368667,0.346007,0.207593,0.207593,0.146539,...,0.146539,0.146539,0.146539,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461,0.150461
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df['prognosis'].unique(), len(df['prognosis'].unique())

(array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
        'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
        'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
        'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
        'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
        'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
        'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
        'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
        'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
        'Osteoarthristis', 'Arthritis',
        '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
        'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object),
 41)

sns.pairplot(df)
plt.show()

In [9]:
X = df.drop('prognosis',axis=1)
X.tail(2)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [10]:
y = df['prognosis']
y.tail(2)

4918    Psoriasis
4919     Impetigo
Name: prognosis, dtype: object

### Train Test Split

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(y)
y = encoder.transform(y)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [12]:
print("X_train Shape:",X_train.shape)
print("X_test Shape:",X_test.shape)
print("y_train Shape:",y_train.shape)
print("y_test Shape:",y_test.shape)

X_train Shape: (3444, 132)
X_test Shape: (1476, 132)
y_train Shape: (3444,)
y_test Shape: (1476,)

In [13]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

models = {
    "SVC":SVC(kernel='linear'),
    "Random Forest Classifier":RandomForestClassifier(n_estimators=100,random_state=100),
    "Decision Tree Classifier":DecisionTreeClassifier(),
    "Gradient Boosting Classifier":GradientBoostingClassifier(n_estimators=100,random_state=100),
    "Multinomial NB":MultinomialNB(),
    "K-Neighbors Classifier":KNeighborsClassifier(n_neighbors=5)
}

for model_name, model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    mat = confusion_matrix(y_test,y_pred)
    
    # Calculate confusion matrix
    print(f"{model_name} Accuracy: {acc}")
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(mat, separator=', '))
    print("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")

SVC Accuracy: 1.0
SVC Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Random Forest Classifier Accuracy: 1.0
Random Forest Classifier Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Decision Tree Classifier Accuracy: 1.0
Decision Tree Classifier Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Gradient Boosting Classifier Accuracy: 1.0
Gradient Boosting Classifier Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Multinomial NB Accuracy: 1.0
Multinomial NB Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
K-Neighbors Classifier Accuracy: 1.0
K-Neighbors Classifier Confusion Matrix:
[[32,  0,  0, ...,  0,  0,  0],
 [ 0, 39,  0, ...,  0,  0,  0],
 [ 0,  0, 41, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 36,  0,  0],
 [ 0,  0,  0, ...,  0, 37,  0],
 [ 0,  0,  0, ...,  0,  0, 39]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

##### Here All models Accuracy is 100%. I will take any one of them.

In [14]:
# selecting svc
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
ypred = svc.predict(X_test)
accuracy_score(y_test,y_pred)

1.0

In [15]:
## Saving model in pkl file..
import pickle
pickle.dump(svc,open('models/svc.pkl','wb'))

In [16]:
## Load model
svc = pickle.load(open('models/svc.pkl','rb'))

In [17]:
# test 1:
print("predicted disease :",svc.predict(X_test.iloc[0].values.reshape(1,-1)))
print("Actual Disease :", y_test[0])

predicted disease : [2]
Actual Disease : 2

In [ ]:
# test 1:
print("predicted disease :",svc.predict(X_test.iloc[0].values.reshape(1,-1)))
print("Actual Disease :", y_test[0])

predicted disease : [23]
Actual Disease : 23

In [ ]:
Symptom_severity_df = pd.read_csv('Datasets/Symptom-severity.csv')
symtoms_df = pd.read_csv('Datasets/symtoms_df.csv')
description_df = pd.read_csv('Datasets/description.csv')
diets_df = pd.read_csv('Datasets/diets.csv')
medications_df = pd.read_csv('Datasets/medications.csv')
precautions_df = pd.read_csv('Datasets/precautions_df.csv')
workout_df = pd.read_csv('Datasets/workout_df.csv')

In [20]:
Symptom_severity_df.head(2)

     Symptom  weight
0    itching       1
1  skin_rash       3

In [21]:
symtoms_df.head(2)

,Unnamed: 0,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN

In [22]:
description_df.head(2)

            Disease                                        Description
0  Fungal infection  Fungal infection is a common skin condition ca...
1           Allergy  Allergy is an immune system reaction to a subs...

In [23]:
diets_df.head(2)

            Disease                                               Diet
0  Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1           Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...

In [24]:
medications_df.head(2)

            Disease                                         Medication
0  Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1           Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...

In [25]:
precautions_df.head(2)

,Unnamed: 0,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out

In [26]:
workout_df.head(2)

   Unnamed: 0.1  Unnamed: 0           disease             workout
0             0           0  Fungal infection  Avoid sugary foods
1             1           1  Fungal infection  Consume probiotics

In [27]:
print("Total Columns / Symptoms : ",len(df.columns)-1)   ## -1 'output column not  countable'
print(f"Toal Classes / Diseases : {len(df['prognosis'].unique())}")

Total Columns / Symptoms :  132
Toal Classes / Diseases : 41

In [28]:
## In encoder the diseases categorical values replace with numbers.
diseases_dict = dict(zip(encoder.transform(encoder.classes_), encoder.classes_))

In [29]:
diseases_dict

{np.int64(0): '(vertigo) Paroymsal  Positional Vertigo',
 np.int64(1): 'AIDS',
 np.int64(2): 'Acne',
 np.int64(3): 'Alcoholic hepatitis',
 np.int64(4): 'Allergy',
 np.int64(5): 'Arthritis',
 np.int64(6): 'Bronchial Asthma',
 np.int64(7): 'Cervical spondylosis',
 np.int64(8): 'Chicken pox',
 np.int64(9): 'Chronic cholestasis',
 np.int64(10): 'Common Cold',
 np.int64(11): 'Dengue',
 np.int64(12): 'Diabetes ',
 np.int64(13): 'Dimorphic hemmorhoids(piles)',
 np.int64(14): 'Drug Reaction',
 np.int64(15): 'Fungal infection',
 np.int64(16): 'GERD',
 np.int64(17): 'Gastroenteritis',
 np.int64(18): 'Heart attack',
 np.int64(19): 'Hepatitis B',
 np.int64(20): 'Hepatitis C',
 np.int64(21): 'Hepatitis D',
 np.int64(22): 'Hepatitis E',
 np.int64(23): 'Hypertension ',
 np.int64(24): 'Hyperthyroidism',
 np.int64(25): 'Hypoglycemia',
 np.int64(26): 'Hypothyroidism',
 np.int64(27): 'Impetigo',
 np.int64(28): 'Jaundice',
 np.int64(29): 'Malaria',
 np.int64(30): 'Migraine',
 np.int64(31): 'Osteoarthristis',
 np.int64(32): 'Paralysis (brain hemorrhage)',
 np.int64(33): 'Peptic ulcer diseae',
 np.int64(34): 'Pneumonia',
 np.int64(35): 'Psoriasis',
 np.int64(36): 'Tuberculosis',
 np.int64(37): 'Typhoid',
 np.int64(38): 'Urinary tract infection',
 np.int64(39): 'Varicose veins',
 np.int64(40): 'hepatitis A'}

In [30]:
## In encoder the symptoms categorical values replace with numbers
symptoms_dict = {symptom: idx for idx, symptom in enumerate(X.columns)}
print("\nSymptoms dictionary:")
print(symptoms_dict)
print(len(symptoms_dict))

Symptoms dictionary:
{'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
132

In [31]:
def get_predicted_symptoms(patient_symptoms):
    input_vect = np.zeros(len(symptoms_dict))
    
    for item in patient_symptoms:
        input_vect[symptoms_dict[item]]=1
    return diseases_dict[svc.predict([input_vect])[0]]

In [32]:
input_patient_1 = "itching,yellow_crust_ooze,swollen_blood_vessels,nodal_skin_eruptions,skin_rash"
pred_1 = get_predicted_symptoms(input_patient_1.split(','))
pred_1

'Fungal infection'

In [33]:
input_patient_2 = "shivering,chills,joint_pain,stomach_pain,acidity"
pred_2 = get_predicted_symptoms(input_patient_2.split(','))
pred_2

'Allergy'

In [1]:
decs_1 = description_df[description_df['Disease']==pred_1]['Description']
''.join(decs_1)

NameError: name 'description_df' is not defined

In [35]:
decs_2 = description_df[description_df['Disease']==pred_2]['Description']
''.join(decs_2)

'Allergy is an immune system reaction to a substance in the environment.'

In [36]:
diets_1 = diets_df[diets_df["Disease"]==pred_1]['Diet']
''.join(diets_1)

"['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"

In [37]:
diets_2 = diets_df[diets_df['Disease']==pred_2]['Diet']
''.join(diets_2)

"['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']"

In [38]:
medication_1 = medications_df[medications_df['Disease']==pred_1]['Medication']
''.join(medication_1)

"['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"

In [39]:
medication_2 = medications_df[medications_df["Disease"]==pred_2]['Medication']
''.join(medication_2)

"['Antihistamines', 'Decongestants', 'Epinephrine', 'Corticosteroids', 'Immunotherapy']"

In [40]:
precautions_1 = precautions_df[precautions_df["Disease"]==pred_1][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']]
[i for i in precautions_1.values]

[array(['bath twice', 'use detol or neem in bathing water',
        'keep infected area dry', 'use clean cloths'], dtype=object)]

In [41]:
precautions_2 = precautions_df[precautions_df['Disease']==pred_2][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']]
[i for i in precautions_2.values]

[array(['apply calamine', 'cover area with bandage', nan,
        'use ice to compress itching'], dtype=object)]

In [42]:
workout_1 = workout_df[workout_df['disease']==pred_1]['workout']
[i for i in workout_1]

['Avoid sugary foods',
 'Consume probiotics',
 'Increase intake of garlic',
 'Include yogurt in diet',
 'Limit processed foods',
 'Stay hydrated',
 'Consume green tea',
 'Eat foods rich in zinc',
 'Include turmeric in diet',
 'Eat fruits and vegetables']

In [43]:
workout_2 = workout_df[workout_df['disease']==pred_2]['workout']
[i for i in workout_2]

['Avoid allergenic foods',
 'Consume anti-inflammatory foods',
 'Include omega-3 fatty acids',
 'Stay hydrated',
 'Eat foods rich in vitamin C',
 'Include quercetin-rich foods',
 'Consume local honey',
 'Limit processed foods',
 'Include ginger in diet',
 'Avoid artificial additives']

In [44]:
def get_predicted_symptoms(patient_symptoms):
    input_vect = np.zeros(len(symptoms_dict))
    
    for item in patient_symptoms:
        input_vect[symptoms_dict[item]]=1
    return diseases_dict[svc.predict([input_vect])[0]]

def symptoms_details(disease):
    desc = description_df[description_df['Disease']==disease]['Description']
    desc = ''.join(desc)
    
    diet = diets_df[diets_df["Disease"]==disease]['Diet']
    diet = [i for i in diet.values.flatten()]
    
    medct = medications_df[medications_df['Disease']==disease]['Medication']
    medct = [i for i in medct.values.flatten()]
    
    prec= precautions_df[precautions_df["Disease"]==disease][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']]
    prec = [i for i in prec.values.flatten()]
    
    workout = workout_df[workout_df['disease']==disease]['workout']
    workout = [i for i in workout]
    
    return desc, diet, medct, prec, workout

In [45]:
patient_input = input("Enter Symptoms : ")   # itching,yellow_crust_ooze,swollen_blood_vessels,nodal_skin_eruptions,skin_rash
print("="*60)
disease = get_predicted_symptoms(patient_input.split(','))
desc, diet, medct, prec, workout = symptoms_details(disease)

print("`"*60)
print("="*20," Disease ","="*20)
print(disease)
print()

print("="*20," Description ","="*20)
print(desc)
print()


print("="*20," precautions ","="*20)
#print(prec)
k=1
for p_k in prec:
    print(f"{k} : {p_k}")
    k+=1
print()

print("="*20," Diets ","="*20)
#print(diet)
i=1
for d_i in diet:
    print(f"{i} : {d_i}")
    i+=1
print()

print("="*20," Medication ","="*20)
#print(medct)
j=1
for m_j in medct:
    print(f"{j} : {m_j}")
    j+=1
print()

print("="*20," Workout ","="*20)
#print(workout)
l=1
for w_l in workout:
    print(f"{l} : {w_l}")
    l+=1
print()

============================================================
````````````````````````````````````````````````````````````
====================  Disease  ====================
Impetigo

====================  Description  ====================
Impetigo is a highly contagious skin infection causing red sores that can break open.

====================  precautions  ====================
1 : soak affected area in warm water
2 : use antibiotics
3 : remove scabs with wet compressed cloth
4 : consult doctor

====================  Diets  ====================
1 : ['Impetigo Diet', 'Antibiotic treatment', 'Fruits and vegetables', 'Hydration', 'Protein-rich foods']

====================  Medication  ====================
1 : ['Topical antibiotics', 'Oral antibiotics', 'Antiseptics', 'Ointments', 'Warm compresses']

====================  Workout  ====================
1 : Maintain good hygiene
2 : Stay hydrated
3 : Consume nutrient-rich foods
4 : Limit sugary foods and beverages
5 : Include foods rich in vitamin C
6 : Consult a healthcare professional
7 : Follow medical recommendations
8 : Avoid scratching
9 : Take prescribed antibiotics
10 : Practice wound care

In [4]:
# ==========================================
# Swasth Disease Prediction Model Trainer
# ==========================================

import pandas as pd
import numpy as np
import pickle
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# ==========================================
# 1️⃣ Load Dataset
# ==========================================

print("Loading dataset...")

DATA_PATH = "Datasets/Training.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError("Training.csv not found inside Datasets folder")

df = pd.read_csv(DATA_PATH)

# Remove unnamed columns if present
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

# Separate features and target
X = df.drop("prognosis", axis=1)
y = df["prognosis"]

print("Total samples:", len(df))
print("Total symptoms (features):", len(X.columns))
print("Total diseases:", len(y.unique()))

# ==========================================
# 2️⃣ Encode Target Labels
# ==========================================

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# ==========================================
# 3️⃣ Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

# ==========================================
# 4️⃣ Train SVC Model
# ==========================================

print("Training SVC model...")

model = SVC(
    kernel="linear",
    probability=True,
    random_state=42
)

model.fit(X_train, y_train)

# ==========================================
# 5️⃣ Evaluate Model
# ==========================================

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", round(accuracy * 100, 2), "%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ==========================================
# 6️⃣ Create Symptoms Dictionary
# ==========================================

# Create mapping of symptom name → index
symptoms_dict = {
    symptom: index
    for index, symptom in enumerate(X.columns)
}

print("\nSymptoms dictionary created.")
print("Total symptoms mapped:", len(symptoms_dict))

# ==========================================
# 7️⃣ Save Model Files
# ==========================================

MODELS_DIR = "models"

if not os.path.exists(MODELS_DIR):
    os.makedirs(MODELS_DIR)

# Save trained model
with open(os.path.join(MODELS_DIR, "svc.pkl"), "wb") as f:
    pickle.dump(model, f)

# Save label encoder
with open(os.path.join(MODELS_DIR, "label_encoder.pkl"), "wb") as f:
    pickle.dump(encoder, f)

# Save symptoms dictionary
with open(os.path.join(MODELS_DIR, "symptoms_dict.pkl"), "wb") as f:
    pickle.dump(symptoms_dict, f)

print("\nAll files saved successfully inside /models folder:")
print(" - svc.pkl")
print(" - label_encoder.pkl")
print(" - symptoms_dict.pkl")

print("\nTraining completed successfully.")

Loading dataset...
Total samples: 4920
Total symptoms (features): 132
Total diseases: 41
Training set shape: (3936, 132)
Testing set shape: (984, 132)
Training SVC model...

Model Accuracy: 100.0 %

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        24
           3       1.00      1.00      1.00        24
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        24
           6       1.00      1.00      1.00        24
           7       1.00      1.00      1.00        24
           8       1.00      1.00      1.00        24
           9       1.00      1.00      1.00        24
          10       1.00      1.00      1.00        24
          11       1.00      1.00      1.00        24
          12       1.00      1.00      1.00        24
          13       1.00      1.00      1.00        24
          14       1.00      1.00      1.00        24
          15       1.00      1.00      1.00        24
          16       1.00      1.00      1.00        24
          17       1.00      1.00      1.00        24
          18       1.00      1.00      1.00        24
          19       1.00      1.00      1.00        24
          20       1.00      1.00      1.00        24
          21       1.00      1.00      1.00        24
          22       1.00      1.00      1.00        24
          23       1.00      1.00      1.00        24
          24       1.00      1.00      1.00        24
          25       1.00      1.00      1.00        24
          26       1.00      1.00      1.00        24
          27       1.00      1.00      1.00        24
          28       1.00      1.00      1.00        24
          29       1.00      1.00      1.00        24
          30       1.00      1.00      1.00        24
          31       1.00      1.00      1.00        24
          32       1.00      1.00      1.00        24
          33       1.00      1.00      1.00        24
          34       1.00      1.00      1.00        24
          35       1.00      1.00      1.00        24
          36       1.00      1.00      1.00        24
          37       1.00      1.00      1.00        24
          38       1.00      1.00      1.00        24
          39       1.00      1.00      1.00        24
          40       1.00      1.00      1.00        24

    accuracy                           1.00       984
   macro avg       1.00      1.00      1.00       984
weighted avg       1.00      1.00      1.00       984


Symptoms dictionary created.
Total symptoms mapped: 132

All files saved successfully inside /models folder:
 - svc.pkl
 - label_encoder.pkl
 - symptoms_dict.pkl

Training completed successfully.